version: "3.7"

services:
  app:
    image: wg-ui:latest
    entrypoint: "/wireguard-ui"
    command: --auth-user-header="X-Request-ID"
    privileged: true
    network_mode: "host"
    volumes:
      - /opt/wireguard-ui:/data
    environment:
      - WIREGUARD_UI_LISTEN_ADDRESS=127.0.0.1:8000
      - WIREGUARD_UI_LOG_LEVEL=debug
      - WIREGUARD_UI_DATA_DIR=/data
      - WIREGUARD_UI_WG_ENDPOINT=cloudburst.example.nl:51820
      - WIREGUARD_UI_CLIENT_IPV4_RANGE=192.168.10.0/24
      - WIREGUARD_UI_CLIENT_IPV6_RANGE=fd00:10::/64
      - "WIREGUARD_UI_WG_DNS=192.168.10.0, fd00:10::"
      - WIREGUARD_UI_IPV6=true
      - WIREGUARD_UI_V6=true
      - WIREGUARD_UI_NAT=true
      - WIREGUARD_UI_NAT_DEVICE=eth0
      - WIREGUARD_UI_WG_DEVICE_NAME=wg0
    restart: always
